-- Create a table for cultivation records
create table records (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  date text,
  type text,
  crop text,
  detail text,
  amount text,
  field text,
  time_start text,
  time_end text,
  range text,
  pesticide text,
  work_type text,
  memo text,
  images text[] -- Array of image URLs
);

-- Create a table for inventory
create table inventory (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  name text,
  category text,
  quantity numeric,
  unit text
);

-- Enable Row Level Security (RLS)
alter table records enable row level security;
alter table inventory enable row level security;

-- Create policies (allow users to see/edit only their own data)
create policy "Users can view their own records" on records for select using (auth.uid() = user_id);
create policy "Users can insert their own records" on records for insert with check (auth.uid() = user_id);
create policy "Users can update their own records" on records for update using (auth.uid() = user_id);

create policy "Users can view their own inventory" on inventory for select using (auth.uid() = user_id);
create policy "Users can insert their own inventory" on inventory for insert with check (auth.uid() = user_id);
create policy "Users can update their own inventory" on inventory for update using (auth.uid() = user_id);
