-- Complete Schema for Agri Compath MVP

-- 1. Profiles (Extends auth.users)
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  name text,
  avatar_url text,
  region text,
  bio text,
  certification_number text,
  ja_member_id text,
  is_public boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Fields (圃場)
create table public.fields (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  type text, -- 'greenhouse', 'field', 'paddy'
  area numeric,
  area_unit text default 'a',
  location_lat numeric,
  location_lng numeric,
  address text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Crop Settings (作物ごとの設定)
create table public.crop_settings (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  crop_name text not null,
  work_types text[], -- Array of custom work types
  pests text[],      -- Array of common pests
  diseases text[],   -- Array of common diseases
  varieties text[],  -- Array of varieties
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, crop_name)
);

-- 4. Inventory (在庫)
create table public.inventory (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  category text, -- 'pesticide', 'fertilizer', 'fuel', 'seed'
  quantity numeric default 0,
  unit text,
  capacity numeric, -- e.g., 500
  capacity_unit text, -- e.g., ml
  expiry_date date,
  location text,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Records (記録)
create table public.records (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  date date default CURRENT_DATE,
  type text, -- 'work', 'pesticide', 'fertilizer', 'harvest', 'tweet'
  crop text,
  field text,
  
  -- Work Details
  work_type text,
  time_start time,
  time_end time,
  duration integer, -- minutes
  
  -- Application Details (Pesticide/Fertilizer)
  pesticide text, -- Main agent name
  fertilizer text, -- Main agent name
  amount numeric,
  unit text,
  dilution integer,
  method text, -- 'spray', 'manual'
  target text, -- pest/disease target
  
  -- Detailed Components (JSONB for flexibility)
  components jsonb, -- { "n": 10, "p": 10, "k": 10 }
  mixes jsonb, -- Array of mixed agents: [{name: 'X', amount: 100}]
  
  -- Harvest
  yield_amount numeric,
  yield_unit text,
  quality text,
  
  -- Common
  memo text,
  images text[],
  range text, -- 'all', 'partial'
  
  -- Sharing
  is_public boolean default true,
  shared_communities text[] -- Array of community IDs
);

-- 6. Communities
create table public.communities (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  region text,
  code text unique, -- Invitation code
  created_by uuid references auth.users,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.community_members (
  id bigint generated by default as identity primary key,
  community_id bigint references public.communities not null,
  user_id uuid references auth.users not null,
  role text default 'member', -- 'admin', 'member'
  joined_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(community_id, user_id)
);

-- 7. Enable RLS
alter table profiles enable row level security;
alter table fields enable row level security;
alter table crop_settings enable row level security;
alter table inventory enable row level security;
alter table records enable row level security;
alter table communities enable row level security;
alter table community_members enable row level security;

-- 8. Basic Policies (Shorthand for brevity - in production, defined carefully)
create policy "Public Access" on profiles for select using (true);
create policy "User Update Own Profile" on profiles for update using (auth.uid() = id);

create policy "User Access Own Fields" on fields for all using (auth.uid() = user_id);
create policy "User Access Own Crop Settings" on crop_settings for all using (auth.uid() = user_id);
create policy "User Access Own Inventory" on inventory for all using (auth.uid() = user_id);
create policy "User Access Own Records" on records for all using (auth.uid() = user_id);

create policy "Community View" on communities for select using (true);
