-- Create communities table
create table communities (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  created_by uuid references auth.users not null,
  image_url text
);

-- Create community_members table
create table community_members (
  id bigint generated by default as identity primary key,
  joined_at timestamp with time zone default timezone('utc'::text, now()) not null,
  community_id bigint references communities on delete cascade not null,
  user_id uuid references auth.users not null,
  role text default 'member', -- 'admin', 'member'
  unique(community_id, user_id)
);

-- Create community_posts table (for chat/timeline)
create table community_posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  community_id bigint references communities on delete cascade not null,
  user_id uuid references auth.users not null,
  content text,
  image_url text
);

-- Create record_shares table (to track which records are shared with which communities)
create table record_shares (
  id bigint generated by default as identity primary key,
  shared_at timestamp with time zone default timezone('utc'::text, now()) not null,
  record_id bigint references records on delete cascade not null,
  community_id bigint references communities on delete cascade not null,
  unique(record_id, community_id)
);

-- Add is_public column to records table
alter table records add column is_public boolean default false;

-- Enable RLS
alter table communities enable row level security;
alter table community_members enable row level security;
alter table community_posts enable row level security;
alter table record_shares enable row level security;

-- Policies for communities
create policy "Communities are viewable by everyone" on communities for select using (true);
create policy "Authenticated users can create communities" on communities for insert with check (auth.role() = 'authenticated');
create policy "Admins can update their communities" on communities for update using (auth.uid() = created_by);

-- Policies for community_members
create policy "Members are viewable by everyone" on community_members for select using (true);
create policy "Users can join communities" on community_members for insert with check (auth.uid() = user_id);
create policy "Users can leave communities" on community_members for delete using (auth.uid() = user_id);

-- Policies for community_posts
create policy "Members can view posts" on community_posts for select using (
  exists (
    select 1 from community_members
    where community_members.community_id = community_posts.community_id
    and community_members.user_id = auth.uid()
  )
);
create policy "Members can create posts" on community_posts for insert with check (
  exists (
    select 1 from community_members
    where community_members.community_id = community_posts.community_id
    and community_members.user_id = auth.uid()
  )
);

-- Policies for record_shares
create policy "Users can see shares for communities they are in" on record_shares for select using (
  exists (
    select 1 from community_members
    where community_members.community_id = record_shares.community_id
    and community_members.user_id = auth.uid()
  )
  or
  exists (
      select 1 from records
      where records.id = record_shares.record_id
      and records.user_id = auth.uid()
  )
);

create policy "Users can share their own records" on record_shares for insert with check (
  exists (
    select 1 from records
    where records.id = record_shares.record_id
    and records.user_id = auth.uid()
  )
);

-- Update records policy to allow viewing shared records
-- Note: existing policy is "Users can view their own records". We need to add a policy for shared records.
create policy "Users can view public records" on records for select using (is_public = true);

create policy "Users can view records shared to their communities" on records for select using (
  exists (
    select 1 from record_shares
    join community_members on record_shares.community_id = community_members.community_id
    where record_shares.record_id = records.id
    and community_members.user_id = auth.uid()
  )
);
