-- Phase 5 Fix: Ensure Inventory Table Exists & Add Columns

-- 1. Create Inventory Table if it doesn't exist (Missing from previous runs?)
CREATE TABLE IF NOT EXISTS public.inventory (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  name text,
  category text,
  quantity numeric,
  unit text,
  receipt_url text -- Ensure this exists too as used in app
);

-- 2. Enable RLS for Inventory if newly created
ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;

-- 3. Add RLS Policies for Inventory (Safe to run if exists, drops first)
DROP POLICY IF EXISTS "Users can view their own inventory" ON public.inventory;
CREATE POLICY "Users can view their own inventory" ON public.inventory FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own inventory" ON public.inventory;
CREATE POLICY "Users can insert their own inventory" ON public.inventory FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own inventory" ON public.inventory;
CREATE POLICY "Users can update their own inventory" ON public.inventory FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own inventory" ON public.inventory;
CREATE POLICY "Users can delete their own inventory" ON public.inventory FOR DELETE USING (auth.uid() = user_id);

-- 4. Add new columns for Phase 5 (Price, Location)
ALTER TABLE public.inventory 
ADD COLUMN IF NOT EXISTS price NUMERIC,
ADD COLUMN IF NOT EXISTS location TEXT;

-- 5. Add receipt_url column if missing (legacy support)
ALTER TABLE public.inventory 
ADD COLUMN IF NOT EXISTS receipt_url TEXT;
